import java.sql.*;
spring.application.name=frontend
spring.datasource.url=jdbc:postgresql://pg-2334a1bc-wordbridge.b.aivencloud.com:12931/defaultdb?user=avnadmin&password=AVNS_Zv-i_BAZ02xnzfElDIY
spring.datasource.username=avnadmin
spring.datasource.database=defaultdb
spring.data.port=12931
spring.datasource.password=AVNS_Zv-i_BAZ02xnzfElDIY
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect